enhance convert branch name workflow to also output image tag and chart version

diff --git a/.github/workflows/convert-branch-name.yml b/.github/workflows/convert-branch-name.yml
--- a/.github/workflows/convert-branch-name.yml
+++ b/.github/workflows/convert-branch-name.yml
@@ -5,16 +5,22 @@ on:
   workflow_call:
     inputs:
       branch:
-        description: "original branch name"
+        description: "Original branch name"
         required: true
         type: string
     outputs:
       namespace_from_branch:
-        description: "branch in namespace compatible fashion"
-        value: ${{ jobs.convert_branch_name.outputs.namespace_from_branch }}
+        description: "Branch in namespace compatible fashion"
+        value: ${{ jobs.convert_branch_name_to_namespace.outputs.namespace_from_branch }}
+      image_tag_from_branch:
+        description: "Image tag from branch"
+        value: ${{ jobs.convert_branch_name_to_image_tag.outputs.image_tag }}
+      chart_version_from_branch:
+        description: "Chart version from branch"
+        value: ${{ jobs.convert_branch_name_to_chart_version.outputs.chart_version }}
 
 jobs:
-  convert_branch_name:
+  convert_branch_name_to_namespace:
     runs-on: ubuntu-latest
     outputs:
       namespace_from_branch: ${{ steps.create_branch_identifier.outputs.namespace_from_branch }}
@@ -26,3 +32,43 @@ jobs:
           temp=$(echo ${{ inputs.branch }} | sed 's@.*/@@' | tr [A-Z] [a-z] | tr _ - | tr \. - | sed 's/\([[:alpha:]]*-[[:digit:]]*-[[:digit:]]*\).*/\1/' | sed 's/-*$//' | cut -c1-63)
           echo "before:" ${{ inputs.branch }} "-- after: $temp"
           echo "namespace_from_branch=$temp" >> $GITHUB_OUTPUT
+  
+  convert_branch_name_to_image_tag:
+    name: "Convert branch name to image tag"
+    runs-on: ubuntu-latest
+    outputs:
+      image_tag: ${{ steps.create_image_tag.outputs.image_tag }}
+    steps:
+      - id: create_image_tag
+        run: |
+          regex_long='^([[:alpha:]]+?-[[:digit:]]+-[[:digit:]]+)'
+          regex_short='^([[:alpha:]]+?-[[:digit:]]+)'
+          if [[ "${{ inputs.branch }}" =~ $regex_long ]]; then
+            tag="${BASH_REMATCH[1]}"
+          elif [[ "${{ inputs.branch }}" =~ $regex_short ]]; then
+            tag="${BASH_REMATCH[1]}"
+          elif [[ "${{ inputs.branch }}" == 'main' ]]; then
+            tag=""
+          else
+          echo "::error::Couldn't extract ticket from branch" ${{ inputs.branch }} ". If not main the branch name should begin alpha-digit or alpha-digit-digit blocks (e.g. SPSH-1234-test-name or release-1-1-optional-text)"
+            exit 1
+          fi
+          echo "image_tag=${tag}" >> "$GITHUB_OUTPUT"
+
+  convert_branch_name_to_chart_version:
+    name: "Convert branch name to chart version"
+    needs:
+      - convert_branch_name_to_image_tag
+    runs-on: ubuntu-latest
+    outputs:
+      chart_version: ${{ steps.create_chart_version.outputs.chart_version }}
+    steps:
+      - id: create_chart_version
+        run: |
+          timestamp=`echo $(date +'%Y%m%d-%H%M')`
+          if [[ "${{ inputs.branch }}" == 'main' ]]; then
+            chart_version=""
+          else
+            chart_version="0.0.0-$(echo ${{ needs.convert_branch_name_to_image_tag.outputs.image_tag }} | tr [A-Z] [a-z])-${timestamp}"
+          fi
+          echo "chart_version=${chart_version}" >> "$GITHUB_OUTPUT"
